'use client';

import React, { useState } from 'react';
import { DocGenerator, INITIAL_DOCS_1042 } from '@/lib/docs/doc-generator';
import { AutoGeneratedDoc } from '@/types/harness';
import {
  FileText,
  Copy,
  Check,
  Download,
  BookOpen,
  Sparkles,
} from 'lucide-react';

export function DocsPanel() {
  const docs = DocGenerator.getGeneratedDocs();
  const [selectedDocId, setSelectedDocId] = useState<string>(docs[0].id);
  const [copied, setCopied] = useState(false);

  const selectedDoc = docs.find((d) => d.id === selectedDocId) || docs[0];

  const handleCopy = () => {
    navigator.clipboard.writeText(selectedDoc.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden p-4 space-y-3 font-mono text-xs select-none">
      {/* Header */}
      <div className="p-3.5 rounded-xl bg-[var(--bg-panel)] border border-[var(--border-subtle)] flex flex-wrap items-center justify-between gap-3 shadow-xs shrink-0">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-[#38bdf8]/15 border border-[#38bdf8]/30 flex items-center justify-center text-[#38bdf8]">
            <BookOpen className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-bold text-sm text-[var(--text-primary)]">15. Automatic Documentation Engine</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-[#10b981]/15 text-[#10b981] font-bold">
                SYNCED WITH AST
              </span>
            </div>
            <div className="text-[11px] text-[var(--text-muted)] font-sans mt-0.5">
              Automatically synthesizes Architectural Decision Records (ADR), API docs, changelogs, and README diffs from code mutations.
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[var(--bg-canvas)] hover:bg-[var(--bg-subtle)] border border-[var(--border-subtle)] text-[var(--text-primary)] font-semibold transition-colors cursor-pointer text-xs"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-[#10b981]" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Content'}</span>
          </button>
        </div>
      </div>

      {/* Document Selection Tabs & Preview */}
      <div className="flex-1 flex flex-col md:flex-row gap-3 overflow-hidden">
        {/* Document list sidebar */}
        <div className="w-full md:w-64 bg-[var(--bg-panel)] border border-[var(--border-subtle)] rounded-xl p-2 space-y-1 overflow-y-auto shrink-0">
          <div className="px-2 py-1 text-[10px] text-[var(--text-muted)] uppercase tracking-wider font-semibold">
            Generated Artifacts
          </div>
          {docs.map((doc) => (
            <button
              key={doc.id}
              onClick={() => setSelectedDocId(doc.id)}
              className={`w-full p-2 rounded-lg text-left transition-colors cursor-pointer space-y-0.5 ${
                doc.id === selectedDocId
                  ? 'bg-[var(--bg-active)] border border-[var(--border-active)] text-[var(--text-primary)]'
                  : 'hover:bg-[var(--bg-subtle)] text-[var(--text-secondary)]'
              }`}
            >
              <div className="font-bold truncate text-xs">{doc.title}</div>
              <div className="text-[10px] text-[var(--text-muted)] truncate">{doc.filename}</div>
            </button>
          ))}
        </div>

        {/* Markdown Content Viewer */}
        <div className="flex-1 bg-[var(--bg-panel)] border border-[var(--border-subtle)] rounded-xl p-4 overflow-y-auto space-y-3 font-sans">
          <div className="flex items-center justify-between pb-2 border-b border-[var(--border-subtle)] font-mono text-xs">
            <span className="font-bold text-[var(--text-primary)]">{selectedDoc.filename}</span>
            <span className="text-[10px] text-[var(--text-muted)]">Generated at {selectedDoc.updatedTimestamp}</span>
          </div>

          <pre className="p-4 rounded-lg bg-[var(--code-bg)] border border-[var(--border-subtle)] text-[var(--text-primary)] font-mono text-xs leading-relaxed overflow-x-auto whitespace-pre-wrap">
            {selectedDoc.content}
          </pre>
        </div>
      </div>
    </div>
  );
}
