import { Run, RunEvent, AgentState, ForgeTemperature, PlanStep, ToolCall } from '@/types/agent';
import { ModelRouter } from '@/lib/models/gateway';
import { ProofGenerator } from '@/lib/verification/proof-generator';

export const INITIAL_RUN_1042: Run = {
  id: 'run-1042',
  runNumber: 1042,
  taskTitle: 'Fix the failing authentication tests in auth-gateway-service',
  taskDescription: 'Integration test suite fails with HTTP 401 Unauthorized when requesting /api/protected/profile. Trace session token lifecycle, patch the client, and prove zero regressions.',
  repositoryId: 'forge-auth-service',
  branch: 'fix/session-token-forwarding',
  modelId: 'kimi-k2-agent',
  state: 'COMPLETE',
  temperature: 'FORGING',
  createdAt: '2026-09-26T10:42:01Z',
  updatedAt: '2026-09-26T10:42:36Z',
  completedAt: '2026-09-26T10:42:36Z',
  proofId: 'proof-run-1042',
  plan: [
    {
      id: 'step-1',
      title: 'Inspect repository & map auth dependencies',
      description: 'Find references to session creation, middleware verification, and outbound client calls.',
      status: 'completed',
      targetedFiles: ['src/auth/session.ts', 'src/auth/client.ts', 'src/auth/middleware.ts'],
      rationale: 'Understand where token generation diverges from client header generation.',
    },
    {
      id: 'step-2',
      title: 'Reproduce failing test target',
      description: 'Run `tests/integration/auth.test.ts` in isolated sandbox to confirm 401 Unauthorized.',
      status: 'completed',
      targetedFiles: ['tests/integration/auth.test.ts'],
      rationale: 'Verify the baseline test failure state before any code mutation.',
    },
    {
      id: 'step-3',
      title: 'Patch session token forwarding in client',
      description: 'Inject `Authorization: Bearer ${token}` header into `AuthServiceClient.fetchWithAuth`.',
      status: 'completed',
      targetedFiles: ['src/auth/client.ts'],
      rationale: 'Ensure credentials travel across internal RPC / HTTP hops.',
    },
    {
      id: 'step-4',
      title: 'Run targeted verification & regression sweep',
      description: 'Execute targeted test suite, security regression suite, typecheck, and build.',
      status: 'completed',
      targetedFiles: ['tests/integration/auth.test.ts', 'tests/regression/security.test.ts'],
      rationale: 'Provide evidence over claims: proves both the fix works and no security regressions were introduced.',
    },
  ],
  toolCalls: [
    {
      id: 'tc-1',
      tool: 'search_files',
      input: { query: 'fetchWithAuth' },
      output: 'Found 1 match in src/auth/client.ts:23',
      status: 'completed',
      durationMs: 140,
      timestamp: '2026-09-26T10:42:03Z',
    },
    {
      id: 'tc-2',
      tool: 'read_file',
      input: { path: 'src/auth/client.ts' },
      output: 'Read 64 lines from src/auth/client.ts',
      status: 'completed',
      durationMs: 80,
      timestamp: '2026-09-26T10:42:05Z',
    },
    {
      id: 'tc-3',
      tool: 'run_tests',
      input: { filter: 'auth.integration' },
      output: 'FAIL tests/integration/auth.test.ts\nExpected 200, received 401 Unauthorized (authMiddleware rejected missing bearer header)',
      status: 'failed',
      durationMs: 1840,
      timestamp: '2026-09-26T10:42:15Z',
    },
    {
      id: 'tc-4',
      tool: 'edit_file',
      input: {
        path: 'src/auth/client.ts',
        targetText: 'const headers = new Headers(options.headers || {});',
        replacementText: 'const headers = new Headers(options.headers || {});\nif (this.currentSession?.token) { headers.set("Authorization", `Bearer ${this.currentSession.token}`); }',
        reason: 'Forward active session token in outgoing request headers',
      },
      output: 'Successfully applied patch to src/auth/client.ts',
      status: 'completed',
      durationMs: 210,
      timestamp: '2026-09-26T10:42:24Z',
    },
    {
      id: 'tc-5',
      tool: 'run_tests',
      input: { filter: 'all' },
      output: 'PASS tests/unit/session.test.ts\nPASS tests/integration/auth.test.ts\nPASS tests/regression/security.test.ts\n4/4 tests passed.',
      status: 'completed',
      durationMs: 1420,
      timestamp: '2026-09-26T10:42:30Z',
    },
    {
      id: 'tc-6',
      tool: 'run_typecheck',
      input: {},
      output: 'tsc --noEmit: zero diagnostics.',
      status: 'completed',
      durationMs: 820,
      timestamp: '2026-09-26T10:42:33Z',
    },
  ],
  recoveryAttempts: [
    {
      attemptNumber: 1,
      failureCategory: 'Test failure',
      failureMessage: 'tests/integration/auth.test.ts failed with HTTP 401 Unauthorized',
      failingComponent: 'src/auth/client.ts',
      likelyCause: 'Outbound AuthServiceClient does not forward the session bearer token in request headers.',
      correctionStrategy: 'Inject Authorization: Bearer ${session.token} into RequestInit headers in AuthServiceClient.fetchWithAuth().',
      patchApplied: {
        filePath: 'src/auth/client.ts',
        description: 'Forward active session token in outgoing Authorization header',
        diffSnippet: `+ if (this.currentSession && this.currentSession.token) {
+   headers.set('Authorization', \`Bearer \${this.currentSession.token}\`);
+   headers.set('X-Session-ID', this.currentSession.id);
+ }`,
      },
      retestTarget: 'tests/integration/auth.test.ts',
      result: 'passed',
      timestamp: '2026-09-26T10:42:24Z',
    },
  ],
  events: [
    {
      id: 'evt-1',
      runId: 'run-1042',
      timestamp: '10:42:01',
      type: 'task.received',
      title: 'TASK RECEIVED',
      summary: 'Task initialized: "Fix the failing authentication tests in auth-gateway-service"',
      state: 'INTAKE',
      temperature: 'COLD',
    },
    {
      id: 'evt-2',
      runId: 'run-1042',
      timestamp: '10:42:02',
      type: 'repo.scanned',
      title: 'REPOSITORY SCANNED',
      summary: 'AST mapped: 28 files, 42.8k tokens. 5 export symbols indexed.',
      state: 'UNDERSTAND',
      temperature: 'THINKING',
    },
    {
      id: 'evt-3',
      runId: 'run-1042',
      timestamp: '10:42:05',
      type: 'context.gathered',
      title: 'RELEVANT FILES FOUND',
      summary: 'Identified 4 primary context candidates. Top relevance: src/auth/client.ts (98%).',
      state: 'SEARCH',
      temperature: 'THINKING',
    },
    {
      id: 'evt-4',
      runId: 'run-1042',
      timestamp: '10:42:07',
      type: 'plan.created',
      title: 'PLAN CREATED',
      summary: 'Generated 4-step execution strategy with targeted test & regression verification.',
      state: 'PLAN',
      temperature: 'WORKING',
    },
    {
      id: 'evt-5',
      runId: 'run-1042',
      timestamp: '10:42:15',
      type: 'failure.detected',
      title: 'FAILURE DETECTED',
      summary: 'Baseline reproduction test failed with HTTP 401 Unauthorized in auth.integration.test.ts',
      state: 'DIAGNOSE',
      temperature: 'HOT',
    },
    {
      id: 'evt-6',
      runId: 'run-1042',
      timestamp: '10:42:20',
      type: 'failure.diagnosed',
      title: 'RECOVERY STRATEGY GENERATED',
      summary: 'Fingerprint match: AUTH-401-TOKEN-MISSING. Classified as Test failure. Formulation: inject Bearer token into client headers.',
      state: 'RECOVER',
      temperature: 'HOT',
    },
    {
      id: 'evt-7',
      runId: 'run-1042',
      timestamp: '10:42:24',
      type: 'recovery.applied',
      title: 'CODE PATCH APPLIED',
      summary: 'Modified src/auth/client.ts (+14 lines, -2 lines). Working tree updated.',
      state: 'EDIT',
      temperature: 'FORGING',
    },
    {
      id: 'evt-8',
      runId: 'run-1042',
      timestamp: '10:42:30',
      type: 'test.executed',
      title: 'RE-TESTING EXECUTED',
      summary: 'Targeted + regression test pass: 4/4 suites passed (0 failures, 1.42s).',
      state: 'RUN',
      temperature: 'FORGING',
    },
    {
      id: 'evt-9',
      runId: 'run-1042',
      timestamp: '10:42:33',
      type: 'verification.passed',
      title: 'VERIFICATION PASSED',
      summary: 'Typecheck: PASS (tsc --noEmit). Lint: PASS. Production Build: PASS.',
      state: 'VERIFY',
      temperature: 'FORGING',
    },
    {
      id: 'evt-10',
      runId: 'run-1042',
      timestamp: '10:42:36',
      type: 'proof.generated',
      title: 'PROOF GENERATED (VERIFIED ✓)',
      summary: 'Deterministic proof record sealed with SHA256 e3b0c442... 4/4 requirements verified by evidence.',
      state: 'PROVE',
      temperature: 'FORGING',
    },
    {
      id: 'evt-11',
      runId: 'run-1042',
      timestamp: '10:42:36',
      type: 'run.completed',
      title: 'RUN COMPLETED',
      summary: 'Task resolved autonomously with 1 successful recovery attempt and 0 regressions.',
      state: 'COMPLETE',
      temperature: 'FORGING',
    },
  ],
  metrics: {
    totalTokens: 38450,
    promptTokens: 31200,
    completionTokens: 7250,
    totalCostUsd: 0.048,
    totalDurationMs: 35000,
    toolCallsCount: 6,
    testsExecutedCount: 4,
    testsPassedCount: 4,
    filesInspectedCount: 17,
    filesModifiedCount: 1,
    retriesCount: 1,
    contextEfficiencyPercent: 88,
  },
};
