import { PricingPlan } from '@/types/billing';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'FREE',
    name: 'Free',
    englishSubtitle: 'For personal coding and exploration',
    tagline: 'For developers experimenting with open-weight autonomous agents.',
    monthlyPriceInr: 0,
    monthlyPriceUsd: 0,
    yearlyPriceInr: 0,
    yearlyPriceUsd: 0,
    runsLimitMonthly: 25,
    contextLimitTokens: 64_000,
    maxParallelTools: 1,
    modelsIncluded: ['Qwen 2.5 Coder 32B', 'Local / Ollama', 'GLM 4.5 Lite'],
    features: [
      '25 autonomous runs per month',
      'Open-weight models (Qwen, Ollama, GLM)',
      'Single-threaded tool executor',
      'Deterministic verification & proof panel',
      'Public & local repository support',
      'Community failure fingerprint library',
    ],
  },
  {
    id: 'BUILDER',
    name: 'Pro',
    englishSubtitle: 'For individual developers and engineers',
    tagline: 'For engineers shipping features and squashing bugs autonomously.',
    monthlyPriceInr: 999,
    monthlyPriceUsd: 12,
    yearlyPriceInr: 9588,
    yearlyPriceUsd: 115,
    runsLimitMonthly: 150,
    contextLimitTokens: 256_000,
    maxParallelTools: 4,
    modelsIncluded: ['GLM 4.5 Agentic', 'Kimi K2 Agentic', 'Qwen 2.5 Coder 72B', 'BYOK (All)'],
    features: [
      '150 verified runs per month',
      'Kimi K2 & GLM 4.5 agentic models',
      'Multi-attempt failure recovery trace',
      '256k token intelligent context window',
      'Bring Your Own Key (BYOK) enabled',
      'Persistent engineering memory store',
      'Private GitHub/GitLab repositories',
    ],
    recommended: true,
  },
  {
    id: 'PRO',
    name: 'Max',
    englishSubtitle: 'For high-frequency reasoning and complex refactoring',
    tagline: 'For senior engineers tackling complex multi-file architectural tasks.',
    monthlyPriceInr: 2499,
    monthlyPriceUsd: 29,
    yearlyPriceInr: 23988,
    yearlyPriceUsd: 280,
    runsLimitMonthly: 500,
    contextLimitTokens: 1_000_000,
    maxParallelTools: 8,
    modelsIncluded: ['DeepSeek R1 Distill Coder', 'Claude 3.7 Sonnet', 'Kimi K2 1M', 'All Open-Weights'],
    features: [
      '500 verified runs per month',
      'Frontier reasoning models (DeepSeek R1, Claude 3.7)',
      '1,000,000 token context window',
      'Parallel tool & targeted test execution',
      'Advanced failure fingerprint memory matching',
      'Continuous verification with CI/CD webhooks',
      'Proof graph export & audit log signatures',
    ],
  },
  {
    id: 'TEAM',
    name: 'Team',
    englishSubtitle: 'For collaborative engineering teams',
    tagline: 'For engineering teams requiring centralized governance and private sandboxes.',
    monthlyPriceInr: 4999,
    monthlyPriceUsd: 59,
    yearlyPriceInr: 47988,
    yearlyPriceUsd: 570,
    runsLimitMonthly: 'Unlimited',
    contextLimitTokens: 2_000_000,
    maxParallelTools: 16,
    modelsIncluded: ['All Models + Dedicated Self-Hosted GPU Cluster Support'],
    features: [
      'Unlimited verified team runs',
      'Isolated microVM container sandbox per run',
      'Centralized team billing & seat governance',
      'Role-based human-in-the-loop approval gates',
      'SOC2 audit trails and secret isolation',
      'Custom repository indexing & private models',
      'Dedicated Slack / Discord alert bridge',
    ],
  },
  {
    id: 'ENTERPRISE',
    name: 'Enterprise',
    englishSubtitle: 'For organizations with custom security and scale',
    tagline: 'Custom deployment, private VPCs, dedicated compute, and enterprise SLA.',
    monthlyPriceInr: 0,
    monthlyPriceUsd: 0,
    yearlyPriceInr: 0,
    yearlyPriceUsd: 0,
    runsLimitMonthly: 'Unlimited',
    contextLimitTokens: 4_000_000,
    maxParallelTools: 32,
    modelsIncluded: ['Air-Gapped Private Infrastructure & Custom Fine-Tuned Models'],
    features: [
      'Custom deployment & dedicated GPU clusters',
      'Air-gapped VPC and on-premise execution',
      'SSO / SAML 2.0 & SCIM directory sync',
      'Custom model fine-tuning & domain adapters',
      'Dedicated solutions architect & 99.99% uptime SLA',
      'Custom procurement, MSAs, and invoicing',
    ],
  },
];

export function getPlanDisplay(planId: string): { hindiName: string; englishSubtitle: string; label: string; name: string } {
  const plan = PRICING_PLANS.find((p) => p.id === planId) || PRICING_PLANS[1];
  return {
    hindiName: plan.name,
    englishSubtitle: plan.englishSubtitle,
    label: plan.name,
    name: plan.name,
  };
}

