import { EngineeringFact } from '@/types/memory';
import { FailureFingerprint } from '@/types/agent';

export const INITIAL_FAILURE_FINGERPRINTS: FailureFingerprint[] = [
  {
    id: 'fp-1',
    fingerprint: 'AUTH-401-TOKEN-MISSING',
    category: 'Test failure',
    firstSeen: '2026-09-20T08:14:00Z',
    lastSeen: '2026-09-26T10:42:15Z',
    seenCount: 3,
    relatedComponents: ['src/auth/client.ts', 'src/auth/middleware.ts', 'src/auth/session.ts'],
    symptomSummary: 'Outbound HTTP requests fail with 401 Unauthorized because bearer token is not forwarded in request headers.',
    successfulRecoveryTactic: 'Inject `Authorization: Bearer ${session.token}` in AuthServiceClient.fetchWithAuth()',
    confidence: 98,
  },
  {
    id: 'fp-2',
    fingerprint: 'TS-2339-PROPERTY-UNDEFINED',
    category: 'Type failure',
    firstSeen: '2026-09-18T14:22:00Z',
    lastSeen: '2026-09-24T19:05:00Z',
    seenCount: 2,
    relatedComponents: ['src/auth/types.ts', 'src/server/routes.ts'],
    symptomSummary: "Property 'userId' does not exist on type 'AuthenticatedRequest'.",
    successfulRecoveryTactic: 'Cast session payload to AuthSession interface before accessing user attributes.',
    confidence: 94,
  },
  {
    id: 'fp-3',
    fingerprint: 'JEST-TIMEOUT-ASYNC-HANDLE',
    category: 'Timeout',
    firstSeen: '2026-09-15T11:10:00Z',
    lastSeen: '2026-09-22T16:30:00Z',
    seenCount: 4,
    relatedComponents: ['tests/integration/auth.test.ts', 'src/server/routes.ts'],
    symptomSummary: 'A worker process has failed to exit gracefully and has been force exited.',
    successfulRecoveryTactic: 'Add afterAll hook to close mock server handles and invoke jest.clearAllMocks().',
    confidence: 91,
  },
];

export const INITIAL_ENGINEERING_FACTS: EngineeringFact[] = [
  {
    id: 'fact-1',
    statement: 'Tests must be run with pnpm test -- --runInBand for deterministic mock state.',
    source: 'repo_config',
    scope: 'tests',
    confidence: 99,
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
    status: 'approved',
    usageCount: 14,
    lastAppliedRunId: 'run-1042',
  },
  {
    id: 'fact-2',
    statement: 'Auth integration requires in-memory SessionManager map or local mock Redis.',
    source: 'agent_recovery',
    scope: 'auth',
    confidence: 95,
    createdAt: '2026-09-18T14:30:00Z',
    updatedAt: '2026-09-26T10:42:00Z',
    status: 'approved',
    usageCount: 9,
    lastAppliedRunId: 'run-1042',
  },
  {
    id: 'fact-3',
    statement: 'Do not modify auto-generated route schemas in src/generated/ — edit src/server/routes.ts instead.',
    source: 'user_input',
    scope: 'api',
    confidence: 98,
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-20T11:00:00Z',
    status: 'approved',
    usageCount: 6,
  },
  {
    id: 'fact-4',
    statement: 'Production build bundles with tsup targeting NodeNext and ES2022.',
    source: 'repo_config',
    scope: 'build',
    confidence: 92,
    createdAt: '2026-09-22T16:00:00Z',
    updatedAt: '2026-09-22T16:00:00Z',
    status: 'approved',
    usageCount: 12,
  },
];
