import { PricingPlan } from '@/types/billing';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'FREE',
    name: 'आरम्भ',
    englishSubtitle: 'Starter',
    tagline: 'For developers experimenting with open-weight autonomous agents.',
    monthlyPriceInr: 0,
    monthlyPriceUsd: 0,
    yearlyPriceInr: 0,
    yearlyPriceUsd: 0,
    runsLimitMonthly: 25,
    contextLimitTokens: 64_000,
    maxParallelTools: 1,
    modelsIncluded: ['Qwen 2.5 Coder 32B', 'Local / Ollama', 'GLM 4.5 Lite'],
    features: [
      '25 autonomous runs per month',
      'Open-weight models (Qwen, Ollama, GLM)',
      'Single-threaded tool executor',
      'Deterministic verification & proof panel',
      'Public & local repository support',
      'Community failure fingerprint library',
    ],
  },
  {
    id: 'BUILDER',
    name: 'प्रगति',
    englishSubtitle: 'Builder',
    tagline: 'For engineers shipping features and squashing bugs autonomously.',
    monthlyPriceInr: 2399,
    monthlyPriceUsd: 29,
    yearlyPriceInr: 23999,
    yearlyPriceUsd: 290,
    runsLimitMonthly: 150,
    contextLimitTokens: 256_000,
    maxParallelTools: 4,
    modelsIncluded: ['GLM 4.5 Agentic', 'Kimi K2 Agentic', 'Qwen 2.5 Coder 72B', 'BYOK (All)'],
    features: [
      '150 verified runs per month',
      'Kimi K2 & GLM 4.5 agentic models',
      'Multi-attempt failure recovery trace',
      '256k token intelligent context window',
      'Bring Your Own Key (BYOK) enabled',
      'Persistent engineering memory store',
      'Private GitHub/GitLab repositories',
    ],
    recommended: true,
  },
  {
    id: 'PRO',
    name: 'प्रवीण',
    englishSubtitle: 'Professional',
    tagline: 'For senior engineers tackling complex multi-file architectural tasks.',
    monthlyPriceInr: 7999,
    monthlyPriceUsd: 99,
    yearlyPriceInr: 79990,
    yearlyPriceUsd: 990,
    runsLimitMonthly: 500,
    contextLimitTokens: 1_000_000,
    maxParallelTools: 8,
    modelsIncluded: ['DeepSeek R1 Distill Coder', 'Claude 3.7 Sonnet', 'Kimi K2 1M', 'All Open-Weights'],
    features: [
      '500 verified runs per month',
      'Frontier reasoning models (DeepSeek R1, Claude 3.7)',
      '1,000,000 token context window',
      'Parallel tool & targeted test execution',
      'Advanced failure fingerprint memory matching',
      'Continuous verification with CI/CD webhooks',
      'Proof graph export & audit log signatures',
    ],
  },
  {
    id: 'TEAM',
    name: 'दल',
    englishSubtitle: 'Team',
    tagline: 'For engineering teams requiring centralized governance and private sandboxes.',
    monthlyPriceInr: 19999,
    monthlyPriceUsd: 249,
    yearlyPriceInr: 199990,
    yearlyPriceUsd: 2490,
    runsLimitMonthly: 'Unlimited',
    contextLimitTokens: 2_000_000,
    maxParallelTools: 16,
    modelsIncluded: ['All Models + Dedicated Self-Hosted GPU Cluster Support'],
    features: [
      'Unlimited verified team runs',
      'Isolated microVM container sandbox per run',
      'Centralized team billing & seat management',
      'Role-based human-in-the-loop approval gates',
      'SOC2 audit trails and secret isolation',
      'Custom repository indexing & private models',
      'Dedicated Slack / Discord alert bridge',
    ],
  },
];

export function getPlanDisplay(planId: string): { hindiName: string; englishSubtitle: string; label: string } {
  const plan = PRICING_PLANS.find((p) => p.id === planId) || PRICING_PLANS[1];
  return {
    hindiName: plan.name,
    englishSubtitle: plan.englishSubtitle,
    label: `${plan.name} (${plan.englishSubtitle})`,
  };
}

