import { AgentState, ToolCall } from './agent';

// 1. Scope Guard
export type ScopeStatus = 'IN_SCOPE' | 'NEEDS_APPROVAL' | 'BLOCKED';

export interface ScopeGuardRule {
  id: string;
  pattern: string;
  description: string;
  type: 'allow' | 'require_approval' | 'block';
  category: 'file' | 'directory' | 'tool' | 'network' | 'database';
}

export interface ScopeGuardDecision {
  target: string;
  action: 'read' | 'write' | 'execute' | 'delete';
  status: ScopeStatus;
  reason: string;
  ruleMatched?: string;
  timestamp: string;
}

// 2. Task Contract
export interface TaskContractRequirement {
  id: string;
  description: string;
  criterion: string;
  satisfied: boolean;
  evidenceRef?: string;
}

export interface TaskContract {
  id: string;
  taskId: string;
  title: string;
  scopeBoundaries: {
    allowedPaths: string[];
    readOnlyPaths: string[];
    forbiddenPaths: string[];
  };
  constraints: string[];
  expectedDeliverables: string[];
  successCriteria: TaskContractRequirement[];
  agreedTimestamp: string;
  isSealed: boolean;
}

// 7. Stuck Agent Detection
export interface StuckAgentTelemetry {
  isStuck: boolean;
  repeatedActionCount: number;
  lastIdenticalCommand?: string;
  consecutiveFailures: number;
  stallDurationSeconds: number;
  detectedLoopPattern?: string;
  mitigationStrategy?: string;
  status: 'HEALTHY' | 'WARNING' | 'LOOP_DETECTED' | 'PIVOTING';
}

// 8. Checkpoints & Rollback
export interface Checkpoint {
  id: string;
  stepIndex: number;
  name: string;
  description: string;
  timestamp: string;
  gitCommitSha: string;
  filesSnapshot: {
    path: string;
    action: 'created' | 'modified' | 'deleted';
    linesChanged: number;
  }[];
  isRollbackTarget?: boolean;
}

// 10. Security Guard
export interface SecurityAuditResult {
  passed: boolean;
  secretsDetected: {
    pattern: string;
    fileOrCommand: string;
    severity: 'critical' | 'high' | 'medium';
    redactedSnippet: string;
  }[];
  dangerousCommandsBlocked: {
    command: string;
    rule: string;
    severity: 'critical' | 'high';
  }[];
  pathTraversalAttempts: number;
  safeSandboxed: boolean;
  auditedTimestamp: string;
}

// 11. Model Arena
export interface ArenaCandidate {
  modelId: string;
  modelName: string;
  provider: string;
  status: 'completed' | 'running' | 'idle';
  responseSnippet: string;
  tokensTotal: number;
  durationMs: number;
  costUsd: number;
  testsPassed: number;
  testsTotal: number;
  invariantScore: number; // 0 - 100
  isWinner?: boolean;
  summaryRationale: string;
}

// 15. Automatic Documentation
export interface AutoGeneratedDoc {
  id: string;
  type: 'adr' | 'api' | 'changelog' | 'readme';
  title: string;
  filename: string;
  content: string;
  updatedTimestamp: string;
  diffSnippet?: string;
}

// 16. Branching Experiments
export interface BranchingTrial {
  id: string;
  branchName: string;
  tacticName: string;
  description: string;
  status: 'PASSED' | 'FAILED' | 'REJECTED' | 'EVALUATING';
  testsPassed: number;
  testsTotal: number;
  linesAdded: number;
  linesRemoved: number;
  executionMs: number;
  isWinningCandidate: boolean;
  tradeoffs: string[];
}

// 17. Human Approval Gate
export interface HumanApprovalGate {
  id: string;
  actionType: 'FILE_DELETE' | 'SCHEMA_MIGRATION' | 'EXTERNAL_NETWORK' | 'CORE_AUTH_EDIT';
  title: string;
  description: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  targetFiles: string[];
  diffPreview: string;
  requestedAt: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  decidedAt?: string;
  reviewerNotes?: string;
}

// Navigating AI and Supervisor AI Agents
export interface AgentParticipant {
  id: 'navigator' | 'supervisor';
  displayName: string;
  role: string;
  avatarIcon: string; // lucide icon identifier
  color: string;
  badgeLabel: string;
  status: 'IDLE' | 'ACTIVE' | 'AUDITING' | 'VERIFYING';
  currentAction: string;
  stats: Record<string, string | number>;
  recentThoughts: {
    timestamp: string;
    thought: string;
    category: 'plan' | 'audit' | 'safety' | 'navigate' | 'verify';
  }[];
}
