import { AutoGeneratedDoc } from '@/types/harness';

export const INITIAL_DOCS_1042: AutoGeneratedDoc[] = [
  {
    id: 'doc-adr-042',
    type: 'adr',
    title: 'ADR-042: Outbound Bearer Token Forwarding in Service RPC Client',
    filename: 'docs/adr/042-bearer-token-forwarding.md',
    content: `# ADR-042: Outbound Bearer Token Forwarding in Service RPC Client

## Status
Accepted

## Context
Downstream microservice endpoints under \`/api/protected/*\` require authenticated session credentials. Previously, \`AuthServiceClient.fetchWithAuth\` failed to inject the session bearer token into outgoing HTTP headers, resulting in spurious 401 Unauthorized responses.

## Decision
Inject \`Authorization: Bearer \${token}\` directly into \`RequestInit.headers\` inside \`AuthServiceClient\` whenever an active session is loaded. Preserve all external caller headers.

## Consequences
- **Positive:** All internal microservice requests carry authenticated credentials automatically.
- **Positive:** Zero regressions on public unauthenticated endpoints.
- **Security:** Tokens are only attached when a valid local session object exists.`,
    updatedTimestamp: '2026-09-26T10:42:36Z',
  },
  {
    id: 'doc-api-client',
    type: 'api',
    title: 'API Reference: AuthServiceClient.fetchWithAuth',
    filename: 'docs/api/auth-service-client.md',
    content: `## AuthServiceClient.fetchWithAuth

\`\`\`typescript
async fetchWithAuth(url: string, options: RequestInit = {}): Promise<Response>
\`\`\`

### Parameters
- \`url\` *(string)*: Target resource URL.
- \`options\` *(RequestInit)*: Fetch options (method, body, custom headers).

### Headers Injected Automatically
| Header | Value | Condition |
|---|---|---|
| \`Authorization\` | \`Bearer <session.token>\` | Injected if \`this.currentSession?.token\` is present |
| \`X-Session-ID\` | \`<session.id>\` | Injected if \`this.currentSession?.id\` is present |

### Return Value
Returns a \`Promise<Response>\` resolving the standard Fetch response.`,
    updatedTimestamp: '2026-09-26T10:42:36Z',
  },
  {
    id: 'doc-changelog',
    type: 'changelog',
    title: 'CHANGELOG.md Entry (v2.4.1)',
    filename: 'CHANGELOG.md',
    content: `## [2.4.1] - 2026-09-26

### Fixed
- **auth:** Fix 401 Unauthorized in \`AuthServiceClient\` by forwarding active session token in outbound HTTP requests.
- **tests:** Added regression test assertion ensuring invalid HMAC tokens remain strictly rejected.

### Verification
- 4/4 test suites passed.
- Strict TypeScript 5.8 \`tsc --noEmit\` passed with 0 diagnostics.
- Sealed by Parishram Harness Proof SHA-256 \`e3b0c442...\`.`,
    updatedTimestamp: '2026-09-26T10:42:36Z',
  },
  {
    id: 'doc-readme-diff',
    type: 'readme',
    title: 'README.md Architecture Update',
    filename: 'README.md',
    content: `### Authentication Gateway Architecture
\`\`\`
Client Request -> Auth Gateway -> AuthServiceClient -> Protected Microservice
                                      [Bearer Token Forwarded]
\`\`\`
All outbound client requests to internal services automatically inherit authorization headers.`,
    updatedTimestamp: '2026-09-26T10:42:36Z',
  },
];

export class DocGenerator {
  public static getGeneratedDocs(): AutoGeneratedDoc[] {
    return INITIAL_DOCS_1042;
  }
}
